version: '3'

services:
  dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/workspace
    container_name: dev
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true