package dto

type ParticipantStatsDTO struct {
	FirstBloodAssist                bool  `json:"firstBloodAssist"`
	VisionScore                     int64 `json:"visionScore"`
	MagicDamageDealtToChampions     int64 `json:"magicDamageDealtToChampion"`
	DamageDealtToObjectives         int64 `json:"damageDealtToObjectives"`
	TotalTimeCrowdControlDealt      int   `json:"totalTimeCrowdControlDealt"`
	LongestTimeSpentLiving          int   `json:"longestTimeSpentLiving"`
	Perk1Var1                       int   `json:"perk1Var1"`
	Perk1Var2                       int   `json:"perk1Var2"`
	Perk1Var3                       int   `json:"perk1Var3"`
	Perk2Var1                       int   `json:"perk2Var1"`
	Perk2Var2                       int   `json:"perk2Var2"`
	Perk2Var3                       int   `json:"perk2Var3"`
	Perk3Var1                       int   `json:"perk3Var1"`
	Perk3Var2                       int   `json:"perk3Var2"`
	Perk3Var3                       int   `json:"perk3Var3"`
	Perk4Var1                       int   `json:"perk4Var1"`
	Perk4Var2                       int   `json:"perk4Var2"`
	Perk4Var3                       int   `json:"perk4Var3"`
	Perk5Var1                       int   `json:"perk5Var1"`
	Perk5Var2                       int   `json:"perk5Var2"`
	Perk5Var3                       int   `json:"perk5Var3"`
	TripleKills                     int   `json:"tripleKills"`
	NodeNeutralizeAssist            int   `json:"nodeNeutralizeAssist"`
	PlayerScore0                    int   `json:"playerScore0"`
	PlayerScore1                    int   `json:"playerScore1"`
	PlayerScore2                    int   `json:"playerScore2"`
	PlayerScore3                    int   `json:"playerScore3"`
	PlayerScore4                    int   `json:"playerScore4"`
	PlayerScore5                    int   `json:"playerScore5"`
	PlayerScore6                    int   `json:"playerScore6"`
	PlayerScore7                    int   `json:"playerScore7"`
	PlayerScore8                    int   `json:"playerScore8"`
	PlayerScore9                    int   `json:"playerScore9"`
	Kills                           int   `json:"kills"`
	TotalScoreRank                  int   `json:"totalScoreRank"`
	NeutralMinionsKilled            int   `json:"neutralMinionsKilled"`
	DamageDealtToTurrets            int64 `json:"damageDealtToTurrets"`
	PhysicalDamageDealtToChampions  int64 `json:"physicalDamageDealtToChampions"`
	NodeCapture                     int   `json:"nodeCapture"`
	LargestMultiKill                int   `json:"largestMultiKill"`
	TotalUnitsHealed                int   `json:"totalUnitsHealed"`
	WardsKilled                     int   `json:"wardsKilled"`
	LargestCriticalStrike           int   `json:"largestCriticalStrike"`
	LargestKillingSpree             int   `json:"largestKillingSpree"`
	QuadraKills                     int   `json:"quadraKills"`
	TeamObjective                   int   `json:"teamObjective"`
	MagicDamageDealt                int   `json:"magicDamageDealt"`
	Item0                           int   `json:"item0"`
	Item1                           int   `json:"item1"`
	Item2                           int   `json:"item2"`
	Item3                           int   `json:"item3"`
	Item4                           int   `json:"item4"`
	Item5                           int   `json:"item5"`
	Perk0                           int   `json:"perk0"`
	Perk1                           int   `json:"perk1"`
	Perk2                           int   `json:"perk2"`
	Perk3                           int   `json:"perk3"`
	Perk4                           int   `json:"perk4"`
	Perk5                           int   `json:"perk5"`
	DamageSelfMitigated             int64 `json:"damageSelfMitigated"`
	MagicalDamageTaken              int64 `json:"magicDamagetaken"`
	FirstInhibitorKill              bool  `json:"firstInhibitorKill"`
	TrueDamageTaken                 int64 `json:"trueDamageTaken"`
	ParticipantID                   int   `json:"participantId"`
	TotalDamageTaken                int64 `json:"totalDamageTaken"`
	PhysicalDamageDealt             int64 `json:"physicalDamageDealt"`
	SightWardsBoughtInGame          int   `json:"sightWardsBoughtInGame"`
	TotalDamageDealtToChampions     int64 `json:"totalDamageDealtToChampions"`
	PhysicalDamageTaken             int64 `json:"physicalDamageTaken"`
	TotalPlayerScore                int   `json:"totalPlayerScore"`
	Win                             bool  `json:"win"`
	ObjectivePlayerScore            int   `json:"objectivePlayerScore"`
	TotalDamageDealt                int64 `json:"totalDamageDealt"`
	NeutralMinionsKilledEnemyJungle int   `json:"neutralMinionsKilledEnemyJumgle"`
	Deaths                          int   `json:"deaths"`
	WardsPlaced                     int   `json:"wardsPlaced"`
	PerkSubStyle                    int   `json:"perkSubStyle"`
	TurretKills                     int   `json:"turretKills"`
	FirstBloodKill                  bool  `json:"firstBloodKill"`
	TrueDamageDealtToChampions      int64 `json:"trueDamageDealtToChampions"`
	GoldEarned                      int   `json:"goldEarned"`
	KillingSprees                   int   `json:"killingSprees"`
	UnrealKills                     int   `json:"unrealKills"`
	AltarsCaptured                  int   `json:"altarsCaptured"`
	FirstTowerAssist                bool  `json:"firstTowerAssist"`
	FirstTowerKill                  bool  `json:"firstTowerKill"`
	ChampLevel                      int   `json:"champLevel"`
	DoubleKills                     int   `json:"doubleKills"`
	NodeCaptureAssist               int   `json:"nodeCaptureAssist"`
	InhibitorKills                  int   `json:"inhibitorKills"`
	FirstInhibitorAssist            bool  `json:"firstInhibitorAssist"`
	VisionWardsBoughtInGame         int   `json:"visionWardsBoughtInGame"`
	AltarsNeutralized               int   `json:"altarsNeutralized"`
	PentaKills                      int   `json:"pentaKills"`
	TotalHeal                       int64 `json:"totalHeal"`
	TotalMinionsKilled              int   `json:"totalMinionsKilled"`
	TimeCCingOthers                 int64 `json:"timeCCingOthers"`
}
